/**
 * Created by leigero on 2018/5/15.
 */
export const orgData   =   {
    "code": "0",
    "pageNo": 1,
    "pageSize": 10,
    "rowStart": 0,
    "rows": [{
        "ORG_TYPE": "1",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "融信通",
        "SUPPORT_DEDUCT_STATUS": "1",
        "USERNAME": "rxt",
        "ID": "54281855",
        "TRADE_ID": "123123123",
        "PAYER_TYPE": "2"
    }, {
        "ORG_TYPE": "1",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "青海师范大学",
        "SUPPORT_DEDUCT_STATUS": "1",
        "USERNAME": "PT01",
        "ID": "54268525",
        "TRADE_ID": "PT01",
        "PAYER_TYPE": "1"
    }, {
        "ORG_TYPE": "3",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "测试企业",
        "SUPPORT_DEDUCT_STATUS": "0",
        "USERNAME": "soft004",
        "ID": "54268380",
        "TRADE_ID": "soft004",
        "PAYER_TYPE": "2"
    }, {
        "ORG_TYPE": "3",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "测试个人",
        "SUPPORT_DEDUCT_STATUS": "0",
        "USERNAME": "soft003",
        "ID": "54268255",
        "TRADE_ID": "soft003",
        "PAYER_TYPE": "1"
    }, {
        "ORG_TYPE": "1",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "XX理工大学",
        "SUPPORT_DEDUCT_STATUS": "0",
        "USERNAME": "feeTrade12",
        "ID": "54268239",
        "TRADE_ID": "feeTrade12",
        "PAYER_TYPE": "1"
    }, {
        "ORG_TYPE": "1",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "xxx票据测试",
        "SUPPORT_DEDUCT_STATUS": "0",
        "USERNAME": "test12",
        "ID": "54267331",
        "TRADE_ID": "test12",
        "PAYER_TYPE": "1"
    }, {
        "ORG_TYPE": "1",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "test11",
        "SUPPORT_DEDUCT_STATUS": "0",
        "USERNAME": "test11",
        "ID": "54267308",
        "TRADE_ID": "test11",
        "PAYER_TYPE": "2"
    }, {
        "ORG_TYPE": "1",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "乐享天成",
        "SUPPORT_DEDUCT_STATUS": "0",
        "USERNAME": "feeTrade6",
        "ID": "54267306",
        "TRADE_ID": "feeTrade6",
        "PAYER_TYPE": "1"
    }, {
        "ORG_TYPE": "3",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "哈尔滨光明培训中心",
        "SUPPORT_DEDUCT_STATUS": "0",
        "USERNAME": "feeTrade22",
        "ID": "54266948",
        "TRADE_ID": "13415431",
        "PAYER_TYPE": "1"
    }, {
        "ORG_TYPE": "1",
        "IS_SUPPORT_CUSTOM_REC_TEMP": "1",
        "ORG_NAME": "锦州工业学院",
        "SUPPORT_DEDUCT_STATUS": "0",
        "USERNAME": "feeTrade11",
        "ID": "54266946",
        "TRADE_ID": "feeTrade11",
        "PAYER_TYPE": "1"
    }],
    "total": 45
}
